Declare functions before using it
Lately Debian enabled -Werror=implicit-function-declaration, causing the
build to break in a few places. Fix it by declaring functions before
using it, or including the right libraries.

Errors that this commit fixes are:

```
probing.c:236:3: error: implicit declaration of function ‘add_ssid_set’ [-Werror=implicit-function-declaration]
probing.c:237:3: error: implicit declaration of function ‘add_rate_sets’ [-Werror=implicit-function-declaration]
poc.c:152:30: error: implicit declaration of function ‘get_file_lines’ [-Werror=implicit-function-declaration]
poc.c:169:59: error: implicit declaration of function ‘str_to_hex’ [-Werror=implicit-function-declaration]
poc.c:522:30: error: implicit declaration of function ‘toupper’ [-Werror=implicit-function-declaration]
test.c:164:3: error: implicit declaration of function ‘load_greylist’; did you mean ‘test_greylist’? [-Werror=implicit-function-declaration]
```